export const GET_ERRORS = "GET_ERRORS";

// security
export const GET_ERROR_MESSAGE = "GET_ERROR_MESSAGE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";

// post
export const CREATE_NEW_POST = "CREATE_NEW_POST";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_POSTS_IN_FEED = "GET_ALL_POSTS_IN_FEED";

// connections
export const GET_ALL_CONNECTIONS = "GET_ALL_CONNECTIONS";
export const SET_NUM_CONNECTIONS = "SET_NUM_CONNECTIONS";
export const SET_IS_CONNECTED = "SET_IS_CONNECTED";
export const UNCONNECT = "UNCONNECT";

// connection request
export const SEND_CONNECTION_REQUEST = "SEND_CONNECTION_REQUEST";
export const CHECK_CONNECTION_REQUEST_SENT = "CHECK_CONNECTION_REQUEST_SENT";
export const CHECK_CONNECTION_REQUEST_RECEIVED = "CHECK_CONNECTION_REQUEST_RECEIVED";
export const GET_SEND_CONNECTION_REQUESTS = "GET_SEND_CONNECTION_REQUESTS";
export const GET_RECEIVED_CONNECTION_REQUESTS = "GET_RECEIVED_CONNECTION_REQUESTS";
export const ACCEPT_CONNECTION_REQUEST = "ACCEPT_CONNECTION_REQUEST";
export const DELETE_CONNECTION_REQUEST = "DELETE_CONNECTION_REQUEST";
export const CANCEL_CONNECTION_REQUEST = "CANCEL_CONNECTION_REQUEST";

// groups
export const SET_NUM_GROUPS = "SET_NUM_GROUPS";

// publications
export const SET_NUM_PUBLICATIONS = "SET_NUM_PUBLICATIONS";

// contacts
export const SET_FIRST_CONTACT_ID = "SET_FIRST_CONTACT_ID";
export const SET_FIRST_OTHER_CONTACT_ID = "SET_FIRST_OTHER_CONTACT_ID";
export const GET_ALL_CONTACTS = "GET_ALL_CONTACTS";
export const GET_CONTACT = "GET_CONTACT";
export const GET_OTHER_CONTACT_ID = "GET_OTHER_CONTACT_ID";
export const CREATE_CONTACT_IF_NOT_EXIST = "CREATE_CONTACT_IF_NOT_EXIST";

// chat messages
export const CREATE_NEW_CHAT_MESSAGE = "CREATE_NEW_CHAT_MESSAGE";
export const GET_ALL_CHAT_MESSAGES = "GET_ALL_CHAT_MESSAGES";

// education
export const CREATE_NEW_EDUCATION = "CREATE_NEW_EDUCATION";
export const GET_ALL_EDUCATIONS = "GET_ALL_EDUCATIONS";

// user profile
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";